pipeline {

agent any

stages {

stage('Git') {

steps {

git 'YOUR_GITHUB_REPO'

}

}

stage('Docker') {

steps {

sh './scripts/build.sh'

}

}

stage('Terraform') {

steps {

sh './scripts/deploy.sh'

}

}

}

}