pipeline {

agent any

stages {

stage('Git') {

steps {

git https://github.com/ravinderp11/Nginx-Application_Deploy.git

}

}

stage('Docker') {

steps {

sh './scripts/build.sh'

}

}

stage('Terraform') {

steps {

sh './scripts/deploy.sh'

}

}

}

}
